ort:
  analyzer:
    allow_dynamic_versions: true
    enabled_package_managers:
      - Maven
      - Gradle
      - NPM
      - PNPM
      - Yarn
      - Yarn 2+
      - PIP
      - Pipenv
      - Poetry
      - NuGet
      - Bundler
      - Cargo
      - GoMod
      - Composer
      - Pub
      - SBT
      - Stack
      - Swift Package Manager
      - CocoaPods
      - Carthage
      - Conan
      - Bazel
      - Bower
      - Tycho
      - SpdxDocumentFile
      - Unmanaged

  scanner:
    skip_concluded: false
    skip_excluded: false
    archive: true
    detect_license_texts: true
    ignore_patterns: [ ]
    scanners:
      - ScanCode

  advisor:
    enabled: true
    advisors:
      - GitHubSecurityAdvisories

  evaluator:
    enabled: true
    options:
      rules:
        allow_dynamic_versions: true
        rule_set: "rules.kts"
