name: ORT Full Scan (with SCANOSS only)

on:
  workflow_dispatch:
    inputs:
      scan_type:
        description: 'Select scan input type'
        required: true
        default: 'git'
        type: choice
        options:
          - git
          - upload-zip
          - upload-tar
      git_url:
        description: 'Git repository URL (if scan_type is git)'
        required: false

jobs:
  ort-full:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set up Java 21 for ORT
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install scanoss pandas openpyxl pyyaml || true

      - name: Prepare Input Based on Scan Type
        run: |
          if [ "${{ github.event.inputs.scan_type }}" == "upload-zip" ]; then
            mkdir -p uploaded-source
            unzip *.zip -d uploaded-source
            scan_path="uploaded-source"
          elif [ "${{ github.event.inputs.scan_type }}" == "upload-tar" ]; then
            mkdir -p extracted-tar
            tar -xf *.tar* -C extracted-tar
            scan_path="extracted-tar"
          elif [ "${{ github.event.inputs.scan_type }}" == "git" ]; then
            git clone --depth 1 "${{ github.event.inputs.git_url }}" repo-to-scan
            scan_path="repo-to-scan"
          fi
          echo "scan_path=$scan_path" >> $GITHUB_ENV

      - name: Download and Extract ORT CLI
        run: |
          curl -L -o ort.zip https://github.com/oss-review-toolkit/ort/releases/download/54.0.0/ort-54.0.0.zip
          unzip ort.zip -d ort-cli
          chmod +x ort-cli/ort-54.0.0/bin/ort

      - name: Clean Output Folders
        run: |
          rm -rf ort-output
          mkdir -p ort-output/analyzer
          mkdir -p ort-output/scanner
          mkdir -p ort-output/advisor
          mkdir -p ort-output/evaluator
          mkdir -p ort-output/report
          rm -rf /home/runner/.ort

      - name: Copy ORT config into expected path
        run: |
          mkdir -p /home/runner/.ort/config/evaluation
          cp .ort/config/config.yml /home/runner/.ort/config/config.yml || true
          cp .ort/evaluator/rules.kts /home/runner/.ort/config/evaluation/rules.kts || true

      - name: ORT Analyze (dynamically with available managers)
        run: |
          available_pms=""

          if command -v pip &> /dev/null; then
            available_pms="${available_pms}\n  - PIP"
          else
            echo "⚠️ Skipped: PIP (pip not installed)"
          fi

          if command -v gradle &> /dev/null; then
            available_pms="${available_pms}\n  - Gradle"
          else
            echo "⚠️ Skipped: Gradle (gradle not installed)"
          fi

          if command -v npm &> /dev/null; then
            available_pms="${available_pms}\n  - NPM"
          else
            echo "⚠️ Skipped: NPM (npm not installed)"
          fi

          if command -v yarn &> /dev/null; then
            available_pms="${available_pms}\n  - Yarn"
          else
            echo "⚠️ Skipped: Yarn (yarn not installed)"
          fi

          if command -v pod &> /dev/null; then
            available_pms="${available_pms}\n  - CocoaPods"
          else
            echo "⚠️ Skipped: CocoaPods (pod not installed)"
          fi

          echo -e "✅ Enabled package managers:$available_pms"

          mkdir -p /home/runner/.ort/config

          echo -e "analyzer:\n  enabledPackageManagers:$available_pms" > /home/runner/.ort/config/analyzer-configuration.yml

          cat /home/runner/.ort/config/analyzer-configuration.yml  # optional debug

          ort-cli/ort-54.0.0/bin/ort analyze \
            -i "$scan_path" \
            -o ort-output/analyzer || true


      - name: Run ORT Evaluate (if advisor result exists)
        run: |
          if [ -f ort-output/advisor/advisor-result.yml ]; then
            ort-cli/ort-54.0.0/bin/ort evaluate               -i ort-output/advisor/advisor-result.yml               -o ort-output/evaluator               --rules-file /home/runner/.ort/config/evaluation/rules.kts || true
          fi
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: ORT WebApp Report (flexible input support)
        run: |
          inputs=""
          if [ -f ort-output/analyzer/analyzer-result.yml ]; then
            inputs="$inputs -i ort-output/analyzer/analyzer-result.yml"
          fi
          if [ -f ort-output/advisor/advisor-result.yml ]; then
            inputs="$inputs -i ort-output/advisor/advisor-result.yml"
          fi
          if [ -f ort-output/evaluator/evaluation-result.yml ]; then
            inputs="$inputs -i ort-output/evaluator/evaluation-result.yml"
          fi

          if [ -n "$inputs" ]; then
            echo "✅ Running ORT report with available inputs: $inputs"
            ort-cli/ort-54.0.0/bin/ort report $inputs -o ort-output/report -f WebApp
          else
            echo "⚠ Skipping WebApp report: No valid input files found."
          fi
        shell: bash
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          ORT_CONFIG_DIR: .ort/config

      - name: Generate Excel Report (ORT + SCANOSS)
        run: |
          python3 generate_excel_from_ort_full.py || echo "⚠️ Report generation finished with fallback or no data, continuing."

      - name: Upload ORT + SCANOSS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ort-full-output
          path: |
            ort-output/
            ort_full_scan_report.xlsx