name: ORT Full Scan (CLI Version)

on:
  workflow_dispatch:
    inputs:
      scan_type:
        description: 'Select scan input type'
        required: true
        default: 'upload-zip'
        type: choice
        options:
          - upload-zip
          - upload-tar
          - git
      git_url:
        description: 'Git repository URL (only required if scan_type is git)'
        required: false

jobs:
  ort-full-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set up Java 21 for ORT
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Download and Extract ORT CLI (v54.0.0)
        run: |
          curl -L --fail --retry 3 -o ort.zip https://github.com/oss-review-toolkit/ort/releases/download/54.0.0/ort-54.0.0.zip
          unzip ort.zip -d ort-cli
          chmod +x ort-cli/ort-54.0.0/bin/ort

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Clean ORT output directories
        run: |
          rm -rf ort-output /home/runner/.ort

      - name: Copy ORT config into expected path
        run: |
          mkdir -p /home/runner/.ort/config
          cp .ort/config/config.yml /home/runner/.ort/config/config.yml

      - name: Extract uploaded ZIP source
        if: ${{ github.event.inputs.scan_type == 'upload-zip' }}
        run: |
          mkdir -p uploaded-source
          unzip "*.zip" -d uploaded-source

      - name: Extract uploaded image TAR
        if: ${{ github.event.inputs.scan_type == 'upload-tar' }}
        run: |
          mkdir -p extracted-tar
          file=$(find . -maxdepth 1 -type f \( -iname "*.tar" -o -iname "*.tar.gz" -o -iname "*.tgz" \) | head -n 1)
          if [ -z "$file" ]; then
            echo "❌ No .tar or .tar.gz file found."
            exit 1
          fi
          tar -xf "$file" -C extracted-tar

      - name: Clone Git Repository to Scan
        if: ${{ github.event.inputs.scan_type == 'git' }}
        run: |
          git clone ${{ github.event.inputs.git_url }} repo-to-scan

      - name: Run ORT Analyzer (even with some failures)
        run: |
          if [ "${{ github.event.inputs.scan_type }}" == "upload-zip" ]; then scan_path="uploaded-source";
          elif [ "${{ github.event.inputs.scan_type }}" == "upload-tar" ]; then scan_path="extracted-tar";
          elif [ "${{ github.event.inputs.scan_type }}" == "git" ]; then scan_path="repo-to-scan"; fi

          mkdir -p ort-output/analyzer/projects
          ort-cli/ort-54.0.0/bin/ort analyze -i "$scan_path" -o ort-output/analyzer/projects || true

      - name: Merge Analyzer Results
        run: |
          mkdir -p ort-output/analyzer
          if compgen -G "ort-output/analyzer/projects/*/analyzer-result.yml" > /dev/null; then
            ort-cli/ort-54.0.0/bin/ort merge-results \
              -i ort-output/analyzer/projects \
              -o ort-output/analyzer
          else
            echo "⚠ No analyzer results found to merge. Skipping merge-results step."
            touch ort-output/analyzer/analyzer-result.yml
          fi

      - name: Install and Run SCANOSS CLI
        run: |
          mkdir -p ort-output/scanner
          curl -L -o scanoss https://github.com/SCANOSS/scanoss.cli/releases/latest/download/scanoss-linux
          chmod +x scanoss
          ./scanoss --src "$scan_path" --output ort-output/scanner/scanoss.spdx.json || echo "⚠ SCANOSS scan failed, continuing."
      
      - name: Run ORT Advisor
        run: |
          ort-cli/ort-54.0.0/bin/ort advise \
            -i ort-output/analyzer/analyzer-result.yml \
            -o ort-output/advisor || echo "⚠ Advisor failed."

      - name: Run ORT Evaluator
        run: |
          ort-cli/ort-54.0.0/bin/ort evaluate \
            -i ort-output/advisor/advisor-result.yml \
            -o ort-output/evaluator || echo "⚠ Evaluator failed."

      - name: Generate WebApp Report
        run: |
          ort-cli/ort-54.0.0/bin/ort report \
            -i ort-output/analyzer/analyzer-result.yml \
            -i ort-output/advisor/advisor-result.yml \
            -i ort-output/evaluator/evaluation-result.yml \
            -o ort-output/report \
            -f WebApp || echo "⚠ WebApp report generation failed."

      - name: Generate Excel from ORT Full Pipeline Output
        run: |
          pip install pyyaml openpyxl pandas || true
          python3 generate_excel_from_ort_full.py ort-output/analyzer/analyzer-result.yml ort-output/evaluator/evaluation-result.yml ort-output/advisor/advisor-result.yml ort-output/scanner/scanoss.spdx.json || echo "⚠ Excel generation failed."

      - name: Upload ORT Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ort-full-pipeline-results
          path: ort-output/
