name: ORT Full Scan (with SCANOSS only)

on:
  workflow_dispatch:
    inputs:
      scan_type:
        description: 'Select scan input type'
        required: true
        default: 'git'
        type: choice
        options:
          - git
          - upload-zip
          - upload-tar

      git_url:
        description: 'Git repository URL (if scan_type is git)'
        required: false

jobs:
  ort-full:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set up Java 21 for ORT
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install scanoss pandas openpyxl || true

      - name: Prepare Input Based on Scan Type
        run: |
          if [ "${{ github.event.inputs.scan_type }}" == "upload-zip" ]; then
            mkdir -p uploaded-source
            unzip *.zip -d uploaded-source
            scan_path="uploaded-source"
          elif [ "${{ github.event.inputs.scan_type }}" == "upload-tar" ]; then
            mkdir -p extracted-tar
            tar -xf *.tar* -C extracted-tar
            scan_path="extracted-tar"
          elif [ "${{ github.event.inputs.scan_type }}" == "git" ]; then
            git clone --depth 1 "${{ github.event.inputs.git_url }}" repo-to-scan
            scan_path="repo-to-scan"
          fi
          echo "scan_path=$scan_path" >> $GITHUB_ENV

      - name: Download and Extract ORT CLI
        run: |
          curl -L -o ort.zip https://github.com/oss-review-toolkit/ort/releases/download/54.0.0/ort-54.0.0.zip
          unzip ort.zip -d ort-cli
          chmod +x ort-cli/ort-54.0.0/bin/ort

      - name: Clean Output Folders
        run: |
          rm -rf ort-output
          mkdir -p ort-output/analyzer
          mkdir -p ort-output/scanner
          mkdir -p ort-output/advisor
          mkdir -p ort-output/evaluator
          mkdir -p ort-output/report
          rm -rf /home/runner/.ort

      - name: Copy ORT Config
        run: |
          mkdir -p /home/runner/.ort/config
          cp .ort/config/config.yml /home/runner/.ort/config/config.yml || true

      - name: ORT Analyze
        run: |
          ort-cli/ort-54.0.0/bin/ort analyze \
            -i "$scan_path" \
            -o ort-output/analyzer || true

      - name: SCANOSS Scan
        run: |
          python3 -m scanoss.cli scan \
            -o ort-output/scanner/scanoss.spdx.json "$scan_path" || echo "⚠ SCANOSS failed"

      - name: ORT Advisor (uses analyzer output only)
        if: ${{ always() }}
        run: |
          if [ -f ort-output/analyzer/analyzer-result.yml ]; then
            ort-cli/ort-54.0.0/bin/ort advise \
              -i ort-output/analyzer/analyzer-result.yml \
              -o ort-output/advisor \
              --advisors OSV || true
          fi

      - name: ORT Evaluate
        if: ${{ always() }}
        run: |
          if [ -f ort-output/advisor/advisor-result.yml ]; then
            ort-cli/ort-54.0.0/bin/ort evaluate \
              -i ort-output/advisor/advisor-result.yml \
              -o ort-output/evaluator || true
          fi

      - name: ORT WebApp Report
        if: ${{ always() }}
        run: |
          if [ -f ort-output/analyzer/analyzer-result.yml ] && \
             [ -f ort-output/advisor/advisor-result.yml ] && \
             [ -f ort-output/evaluator/evaluation-result.yml ]; then
            ort-cli/ort-54.0.0/bin/ort report \
              -i ort-output/analyzer/analyzer-result.yml \
              -i ort-output/advisor/advisor-result.yml \
              -i ort-output/evaluator/evaluation-result.yml \
              -o ort-output/report \
              -f WebApp
          else
            echo "⚠ Skipping WebApp report: Required inputs missing."
          fi

      - name: Upload ORT + SCANOSS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ort-full-output
          path: ort-output/
